services:

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    secrets:
      - db_password
      - credentials

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  static:
    build:
      context: requirements/bonus/static
      dockerfile: Dockerfile
    image: static
    container_name: static
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - inception

  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception

  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    secrets:
      - db_password

  monitor:
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    image: monitor
    container_name: monitor
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/blohrer/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/blohrer/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
